=== SiftScience/sift-dotnet/Sift/Schema/transaction.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Transaction",
  "type": "object",
  "required": [ "$type" ],
  "properties": {
    "$type": {
      "type": "string",
      "default": "$transaction"
    },
    "$user_id": {
      "type": [ "string", "null" ]
    },
    "$session_id": {
      "type": [ "string", "null" ]
    },
    "$user_email": {
      "type": [ "string", "null" ]
    },
    "$transaction_type": {
      "type": [ "string", "null" ]
    },
    "$transaction_status": {
      "type": [ "string", "null" ]
    },
    "$amount": {
      "type": ["integer", "null"],
      "format": "long"
    },
    "$currency_code": {
      "type": [ "string", "null" ]
    },
    "$order_id": {
      "type": [ "string", "null" ]
    },
    "$transaction_id": {
      "type": [ "string", "null" ]
    },
    "$billing_address": {
      "oneOf": [
        { "$ref": "ComplexTypes/address.json" },
        { "type": "null" }
      ]
    },
    "$payment_method": {
      "oneOf": [
        { "$ref": "ComplexTypes/payment_method.json" },
        { "type": "null" }
      ]
    },
    "$shipping_address": {
      "oneOf": [
        { "$ref": "ComplexTypes/address.json" },
        { "type": "null" }
      ]
    },
    "$seller_user_id": {
      "type": [ "string", "null" ]
    },
    "$transfer_recipient_user_id": {
      "type": [ "string", "null" ]
    },
    "$app": {
      "oneOf": [
        { "$ref": "ComplexTypes/app.json" },
        { "type": "null" }
      ]
    },
    "$browser": {
      "oneOf": [
        { "$ref": "ComplexTypes/browser.json" },
        { "type": "null" }
      ]
    },
    "$brand_name": {
      "type": [ "string", "null" ]
    },
    "$site_country": {
      "type": [ "string", "null" ]
    },
    "$site_domain": {
      "type": [ "string", "null" ]
    },
    "$ordered_from": {
      "oneOf": [
        { "$ref": "ComplexTypes/ordered_from.json" },
        { "type": "null" }
      ]
    },
    "$decline_category": {
      "type": [ "string", "null" ]
    },
    "$sent_address": {
        "oneOf": [
            { "$ref": "ComplexTypes/address.json" },
            { "type": "null" }
        ]
    },
    "$received_address": {
        "oneOf": [
            { "$ref": "ComplexTypes/address.json" },
            { "type": "null" }
        ]
    },
    "$status_3ds": {
        "type": [ "string", "null" ]
    },
    "$triggered_3ds": {
        "type": [ "string", "null" ]
    },
    "$merchant_initiated_transaction": {
        "type": [ "boolean", "null" ]
    },
    "$merchant_profile": {
        "oneOf": [
            { "$ref": "ComplexTypes/merchant_profile.json" },
            { "type": "null" }
        ]
    },
    "$keyless_user_id": {
      "type": [ "string", "null" ]
    },
    "$verification_phone_number": {
      "type": [ "string", "null" ]
    }
  }
}

=== SiftScience/sift-dotnet/TestRequestBody/TestTransactionEventWithFintechFields_Transaction.json
{"$type":"$transaction","$user_id":"test_dotnet_transaction_event","$session_id":"sessionId","$transaction_type":"$sale","$transaction_status":"$failure","$amount":1000000000000,"$currency_code":"USD","$payment_method":{"$payment_type":"$sepa_instant_credit","$shortened_iban_first6":"FR7630","$shortened_iban_last4":"1234","$sepa_direct_debit_mandate":true},"$decline_category":"$invalid","$sent_address":{"$name":"Bill Jones","$address_1":"2100 Main Street","$address_2":"Apt 3B","$city":"New London","$region":"New Hampshire","$country":"US","$zipcode":"03257","$phone":"1-415-555-6040"},"$received_address":{"$name":"Bill Jones","$address_1":"2100 Main Street","$address_2":"Apt 3B","$city":"New London","$region":"New Hampshire","$country":"US","$zipcode":"03257","$phone":"1-415-555-6040"},"$status_3ds":"$successful","$triggered_3ds":"$processor","$merchant_initiated_transaction":true,"$merchant_profile":{"$merchant_id":"123","$merchant_category_code":"9876","$merchant_name":"ABC Merchant","$merchant_address":{"$name":"Bill Jones","$address_1":"2100 Main Street","$address_2":"Apt 3B","$city":"New London","$region":"New Hampshire","$country":"US","$zipcode":"03257","$phone":"1-415-555-6040"}}}
